### ISSUE TITLE
Wrong license in pyproject.toml

### ISSUE THREAD

**Issue by pya** [usgs-coupled/phreeqcrm#148]
The `pyproject.toml` says:

    License :: OSI Approved :: GNU General Public License v3 (GPLv3)

but the [LICENSE](https://github.com/usgs-coupled/phreeqcrm/blob/master/LICENSE) says

    Creative Commons Legal Code

    CC0 1.0 Universal

The [PyPi classifiers](https://pypi.org/classifiers/) offers:

    License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication

**Comment by scharlton2** [comment]
Thanks @pya.
