### ISSUE TITLE
Assigning Different EQUILIBRIUM_PHASES to Each Grid in PHREEQCRM

### ISSUE THREAD

**Issue by behzaadh** [usgs-coupled/phreeqcrm#166]
I wonder if it is possible to assign different EQUILIBRIUM_PHASES to each grid in PHREEQCRM. As shown in the attached figure, I have assigned two different EQUILIBRIUM_PHASES for cells 1 and 2. However, it appears that only changing the EQUILIBRIUM_PHASES of cell 1 impacts the overall reaction for all cells.

Here is the phreeqcrm input file:

![image](https://github.com/user-attachments/assets/8146b458-1247-4baa-96e0-0bac6562c3ea)

**Comment by dlparkhurst** [comment]
The method InitialEquilibriumPhases2Module(vector_of_index_numbers) will transfer definitions from the input file read by the InitialPhreeqc instance to the workers. The vector contains equilibrium phases user numbers. The vector has length of the number cells in the transport model. If the vector alternates 1 and 2, then odd cell numbers will receive the definition of EQUILIBRIUM_PHASES 1 and even cell numbers will receive EQUILIBRIUM_PHASES 2. You could define a different equilibrium phases for each cell in the transport model if you want.

**Comment by dlparkhurst** [comment]
Previously, the method InitialPhreeqc2Module to map all solutions and reactants to the model cells. Now it is possible to use methods like InitialSolutions2Module, InitialEquilibriumPhases2Module, and others to map one solution or reactant at a time.
