### ISSUE TITLE
BMIPhreeqcRM::SetValue("Porosity", ...) crashes

### ISSUE THREAD

**Issue by scharlton2** [usgs-coupled/phreeqcrm#55]
Both of these crash

Unit tests have been created but haven't been merged yet.

*** Note that the SetPorosity call doesn't assert ***

It has to do with the concentration vector not being initialized

```C++
#include <cstdlib>
#include "BMIPhreeqcRM.h"

int main(void)
{
    BMIPhreeqcRM* bmi = new BMIPhreeqcRM;

    bmi->Initialize("AdvectBMI_cpp.yaml");

    int nxyz = bmi->GetGridSize(0);
    assert(nxyz == 40);

    std::vector<double> por(40, 0.2);
    //bmi->SetPorosity(por);
    bmi->SetValue("Porosity", por);

    delete bmi;
    return EXIT_SUCCESS;
}
```

```Python
import phreeqcrm as rm
import numpy as np

bmi = rm.bmi_phreeqcrm()

bmi.initialize("AdvectBMI_py.yaml")

nxyz = bmi.get_grid_size(0)
assert(nxyz == 40)

por = np.full((nxyz,), 0.2)
bmi.set_value("Porosity", por)
```

**Comment by dlparkhurst** [comment]
I added code to initialize all the BMI Vars, including the ones causing the unit test error, at the end of FindComponents. I pushed changes to bmi-f90, but had other questions about python yaml.

**Comment by dlparkhurst** [comment]
Actually added at the end of InitializeYAML.
